# Generated by Django 4.2.23 on 2025-09-06 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juntagrico', '0041_1_7'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name dieser Option', max_length=100, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Beitrags-Option',
                'verbose_name_plural': 'Beitrags-Optionen',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ContributionRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Eindeutiger Name dieser Beitragsrunde', max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('other_amount', models.BooleanField(default=False, help_text='Erlaubt dem Mitglied einen eigenen, höhren Betrag anzugeben', verbose_name='Anderen Beitrag erlauben')),
                ('status', models.CharField(choices=[('D', 'Entwurf'), ('A', 'Aktiv'), ('C', 'Geschlossen')], default='D', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Beitragsrunde',
                'verbose_name_plural': 'Beitragsrunden',
            },
        ),
        migrations.CreateModel(
            name='ContributionSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Betrag')),
                ('contact_me', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kontaktiert mich, falls es nicht reicht')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='juntagrico_contribution.contributionround')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='juntagrico_contribution.contributionoption')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='juntagrico.subscription')),
            ],
            options={
                'verbose_name': 'Beitrag',
                'verbose_name_plural': 'Beiträge',
            },
        ),
        migrations.AddField(
            model_name='contributionoption',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='juntagrico_contribution.contributionround'),
        ),
        migrations.CreateModel(
            name='ContributionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Beitrag')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='juntagrico_contribution.contributionoption')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_conditions', to='juntagrico.subscriptiontype')),
            ],
            options={
                'verbose_name': 'Beitrags-Kondition',
                'verbose_name_plural': 'Beitrags-Konditionen',
            },
        ),
        migrations.AddConstraint(
            model_name='contributionselection',
            constraint=models.UniqueConstraint(fields=('round', 'subscription'), name='unique_round_subscription'),
        ),
        migrations.AddConstraint(
            model_name='contributioncondition',
            constraint=models.UniqueConstraint(fields=('option', 'subscription_type'), name='unique_option_type'),
        ),
    ]
