# Generated by Django 4.2.23 on 2025-11-13 19:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionoption',
            name='amount_rounding',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.01'), max_digits=11, verbose_name='Aufrunden auf'),
        ),
        migrations.AddField(
            model_name='contributionround',
            name='contact_me_text',
            field=models.TextField(blank=True, default='Bitte kontaktiert mich, falls es nicht reicht.', help_text='Text bei Abfrage zur Bereitschaft für eine 2. Runde', verbose_name='"Kontaktiert mich" Text'),
        ),
    ]
