# Generated by Django 4.2.23 on 2025-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionround',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Zielbetrag'),
            preserve_default=False,
        ),
    ]
