# Generated by Django 4.2.25 on 2025-12-19 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0002_contributionoption_amount_rounding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionround',
            name='default_amount',
            field=models.ForeignKey(blank=True, help_text='Option für Mitglieder, die kein Gebot abgeben', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_default_for', to='juntagrico_contribution.contributionoption', verbose_name='Standardbetrag'),
        ),
        migrations.AddField(
            model_name='contributionround',
            name='target_multiplier',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Alternativ zum Ziel-Betrag kann hier ein Multiplikator angegeben werden, der mit Nominalbetrag multipliziert wird. Ersetzt den Ziel-Betrag, wenn gesetzt.', max_digits=4, null=True, verbose_name='Ziel-Multiplikator'),
        ),
    ]
