# Generated by Django 4.2.23 on 2025-09-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0002_contributionround_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionoption',
            name='visible',
            field=models.BooleanField(blank=True, default=True, help_text='Diese Option dem Mitglied anzeigen?', verbose_name='Sichtbar'),
        ),
    ]
