# Generated by Django 4.2.23 on 2025-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0003_contributionoption_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionround',
            name='cancellation_cutoff',
            field=models.DateField(blank=True, help_text='Wer erst nach diesem Datum gekündigt hat, nimmt noch an der Beitragsrunde teil.', null=True, verbose_name='Kündigungsfrist'),
        ),
        migrations.AddField(
            model_name='contributionround',
            name='creation_cutoff',
            field=models.DateField(blank=True, help_text='Nur Neubestellungen ab diesem Datum nehmen an der Beitragsrunde teil.', null=True, verbose_name='Nur Neubestellungen ab'),
        ),
    ]
