# Generated by Django 4.2.23 on 2025-09-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0004_contributionround_cancellation_cutoff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionround',
            name='minimum_amount',
            field=models.ForeignKey(blank=True, help_text='Anderer Betrag muss höher sein als diese Option', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='is_minimum_for', to='juntagrico_contribution.contributionoption', verbose_name='Mindestbetrag'),
        ),
        migrations.AlterField(
            model_name='contributionround',
            name='other_amount',
            field=models.BooleanField(default=False, help_text='Erlaubt dem Mitglied einen eigenen, höheren Betrag anzugeben', verbose_name='Anderen Beitrag erlauben'),
        ),
    ]
