# Generated by Django 4.2.23 on 2025-09-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0005_contributionround_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionoption',
            name='multiplier',
            field=models.FloatField(default=1, help_text='Wenn kein expliziter Preis angegeben wird, wird der Preis vom Typ mit diesem Faktor multipliziert.', verbose_name='Multiplikator'),
        ),
    ]
