# Generated by Django 4.2.23 on 2025-09-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juntagrico_contribution', '0006_contributionoption_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionselection',
            name='modification_date',
            field=models.DateField(auto_now=True, verbose_name='Zuletzt geändert'),
        ),
        migrations.AlterField(
            model_name='contributionoption',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='juntagrico_contribution.contributionround', verbose_name='Beitragsrunde'),
        ),
    ]
