name: juntagrico-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release_* ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      DJANGO_SETTINGS_MODULE: testsettings
      PYTHONPATH: .
      CC_TEST_REPORTER_ID: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        pip install --upgrade -r requirements.txt
    - name: ruff
      run: |
        ruff check juntagrico_contribution
    - name: run tests
      run: |
        python -m django makemigrations --noinput
        coverage run -m manage test
    - run: coverage lcov -o coverage.lcov
      if: ${{ matrix.python-version == '3.11' }}
    - uses: qltysh/qlty-action/coverage@v2
      if: ${{ matrix.python-version == '3.11' }}
      with:
        oidc: true
        files: coverage.lcov